Repository Nextera-blog/nextera-front, pull requests merged in 2025-05, with the labels that each got.

#10 Merge feature/03/posts-list-page into develop
  index.html
  package-lock.json
  package.json
  src/components/ArticleCard.tsx
  src/components/Header.tsx
  src/hooks/apiRequest.ts
  src/index.css
  src/pages/App.tsx
  src/pages/ArticlePage.tsx
  src/pages/Home.tsx
  src/router.tsx
  src/types/api.ts
Labels: feature

#11 Merge Feature/10/add-loader-and-logo into develop
  public/loader.gif
  src/components/ArticleCard.tsx
  src/components/Header.tsx
  src/index.css
  src/pages/Home.tsx
  src/router.tsx
Labels: front

#13 Feature/2/page connexion inscription
  src/api/axiosInstance.ts
  src/components/Header.tsx
  src/components/SubmitButton.tsx
  src/contexts/AuthContext.tsx
  src/index.css
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/router.tsx
Labels: feature, front

#15 Merge Kan 13/feature/page-redaction-post into develop
  README.md
  src/components/ArticleCard.tsx
  src/components/Header.tsx
  src/components/NotificationCard.tsx
  src/hooks/apiRequest.ts
  src/index.css
  src/pages/ArticlePage.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/LoginPage.tsx
  src/pages/RedactionArticlePage.tsx
  src/pages/SignUpPage.tsx
  src/router.tsx
Labels: feature, front

#16 Merge MVP application into main branch
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/loader.gif
  public/nextera-logo.png
  src/api/axiosInstance.ts
  src/components/ArticleCard.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/NotificationCard.tsx
  src/components/SubmitButton.tsx
  src/contexts/AuthContext.tsx
  src/hooks/apiRequest.ts
  src/hooks/useGetArticle.ts
  src/index.css
  src/main.tsx
  src/pages/App.tsx
  src/pages/ArticlePage.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/LoginPage.tsx
  src/pages/RedactionArticlePage.tsx
  src/pages/SignUpPage.tsx
  src/router.tsx
  src/types/api.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feature
